version: '3.8'

services:
  monomap-service:
    image: agopdev/monomap-service:latest
    container_name: monomap-service
    environment:
      PORT: 3000
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      MAILER_ACCESS_TOKEN: ${MAILER_ACCESS_TOKEN}
      MAILER_SERVICE: ${MAILER_SERVICE}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27017:27017"
    volumes:
    - mongo_db:/data/db

volumes:
  mongo_db: